/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClientOP;

import dbsecuritysystem.LoginFrame;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Clientregistrationframe extends javax.swing.JFrame {

    /**
     * Creates new form Clientregistrationframe
     */
    public Clientregistrationframe() 
    {
        super("Client Registartion Frame");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("     Name");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 120, 40);

        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(240, 30, 210, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Date of Birth");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 120, 120, 40);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(240, 120, 40, 40);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(300, 120, 50, 40);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(370, 120, 100, 40);

        jLabel4.setText(" DD");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 170, 40, 20);

        jLabel5.setText("  MM");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 170, 50, 20);

        jLabel6.setText(" YYYY");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(390, 170, 51, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("  Mobile no");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 210, 120, 40);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(240, 210, 210, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("   Email id");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 290, 130, 40);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(240, 290, 210, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("  User name");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 380, 130, 40);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(240, 370, 210, 40);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("  Password");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 470, 130, 40);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(246, 470, 200, 40);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Confirm Password");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 550, 150, 40);
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(250, 550, 200, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 630, 90, 50);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(180, 630, 100, 50);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("<<Back");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(330, 630, 100, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(610, 160, 530, 700);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("CLIENT REGISTARTION FORM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(560, 70, 750, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name=jTextField1.getText();
        String Date=jTextField2.getText();
        String month=jTextField3.getText();
        String year=jTextField4.getText();
        String mobilenum=jTextField5.getText();
        String emailid=jTextField6.getText();
        String username=jTextField7.getText();
        String password=jPasswordField1.getText();
        String confpassword=jPasswordField2.getText();
        
        name=name.trim();
        
        Date=Date.trim();
        month=month.trim();
        year=year.trim();
        
        mobilenum=mobilenum.trim();
        emailid=emailid.trim();
        username=username.trim();
        password=password.trim();
        confpassword=confpassword.trim();
        
        
        
        
        if(name.isEmpty())
            JOptionPane.showMessageDialog(null,"Name Cannot be empty");
        
        else if(Date.isEmpty())
            JOptionPane.showMessageDialog(null, "Date should cannot be empty");
        else if(Date.length()!=2)
             JOptionPane.showMessageDialog(null, "Date should be only two digits");
        else if(!new validator().isDigit(Date))
            JOptionPane.showMessageDialog(null, "Date should contains digits only");
        else if(!(Integer.parseInt(Date)>=1 && Integer.parseInt(Date)<=31))
            JOptionPane.showMessageDialog(null,"Date should be in between 1 to 31 only");
        
         else if(month.isEmpty())
            JOptionPane.showMessageDialog(null, "Month should cannot be empty");
        else if(month.length()!=2)
             JOptionPane.showMessageDialog(null, "Month should be only two digits");
        else if(!new validator().isDigit(month))
            JOptionPane.showMessageDialog(null, "Month should contains digits only");
        else if(!(Integer.parseInt(month)>=1 && Integer.parseInt(month)<=12))
            JOptionPane.showMessageDialog(null,"Month should be in between 1 to 12 only");
        
         else if(year.isEmpty())
            JOptionPane.showMessageDialog(null, "Year should cannot be empty");
        else if(year.length()!=4)
             JOptionPane.showMessageDialog(null, "Year should be only two digits");
        else if(!new validator().isDigit(year))
            JOptionPane.showMessageDialog(null, "year should contains digits only");
        
        else if(mobilenum.isEmpty())
            JOptionPane.showMessageDialog(null, "Mobile number should cannot be empty");
        else if(mobilenum.length()!=10)
             JOptionPane.showMessageDialog(null, "Mobile number should be only Ten digits");
        else if(!new validator().isDigit(mobilenum))
            JOptionPane.showMessageDialog(null, "Mobile number should contains digits only");
        
        else if(emailid.isEmpty())
            JOptionPane.showMessageDialog(null,"Email id should not be empty");
        else if(!(emailid.contains(".") &&  emailid.contains("@")) )
            JOptionPane.showMessageDialog(null,"Email id cannot be valid");
        
        else if(username.isEmpty())
             JOptionPane.showMessageDialog(null,"Username should not be empty");
        else if(password.isEmpty())
            JOptionPane.showMessageDialog(null,"Password should not be empty");
         else if(password.length()!=8)
             JOptionPane.showMessageDialog(null, "Password should be only 8 character");
         else if(confpassword.isEmpty())
            JOptionPane.showMessageDialog(null,"Confirm Password should not be empty");
         else if(confpassword.length()!=8)
             JOptionPane.showMessageDialog(null, "Confirm Password should be only 8 character");
         else if(!password.equals(confpassword))
             JOptionPane.showMessageDialog(null,"password and confirm passowrd should not same");
        else
         {
             System.out.println("Name = "+name);
             System.out.println("Date = "+Date);
             System.out.println("Month = "+month);
             System.out.println("Year = "+year);
             System.out.println("Mobilenum = "+mobilenum);
             System.out.println("EmailId = "+emailid);
              System.out.println("Username = "+username);
             System.out.println("Password = "+password);
             System.out.println("Confirm Password = "+confpassword);
             Date dt=new Date();
             SimpleDateFormat sdf=new SimpleDateFormat("DD-MM-YYYY HH:MM:SS");
             String currenttime=sdf.format(dt);
             System.out.println("Current date and time = "+currenttime);
             
             
             
             String dob=Date+"-"+month+"-"+year;
             clientDBOP cdop=new clientDBOP();
             if(cdop.isclientRegister(name, dob, mobilenum, emailid, username, password, currenttime))
                 JOptionPane.showMessageDialog(null,"Successfully inserted....Thank you ");
             else
                 JOptionPane.showMessageDialog(null,"Error Occured!!! ");
             
             jTextField1.setText("");
             jTextField2.setText("");
             jTextField3.setText("");
             jTextField4.setText("");
             jTextField5.setText("");
             jTextField6.setText("");
             jTextField7.setText("");
             jPasswordField1.setText("");
             jPasswordField2.setText("");

             
             
             
             
         }
        
            
            
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LoginFrame lf=new LoginFrame();
       Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
       lf.setVisible(true);
       lf.setSize(d);
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
             jTextField2.setText("");
             jTextField3.setText("");
             jTextField4.setText("");
             jTextField5.setText("");
             jTextField6.setText("");
             jTextField7.setText("");
             jPasswordField1.setText("");
             jPasswordField2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientregistrationframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientregistrationframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientregistrationframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientregistrationframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientregistrationframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
